[package]
name = "symploke"
version = "0.1.0"
edition = "2021"
authors = ["Salvatore Bertino <sabert148@gmail.com>"]

[dependencies]
regex = "1"
once_cell = "1"
itertools = "0.12"


[lib]
name = "symploke"
path = "src/libs/lexer.rs"

[[bin]]
name = "symploke"
path = "src/main.rs"
